# This is a basic workflow to help you get started with Actions

name: metrics

# Controls when the workflow will run
on:
  # Schedule updates (on 8,12,28th each month at 12 A.M)
  schedule: [{cron: "0 12 8,18,28 * *"}]
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # Lines below let you run workflow manually and on each commit:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.SECRET_METRICS }}

          # Options
          ## Basics:
          user: IMpcuong
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Bangkok
          
          ## Achievements:
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          
          ## Followings/Followers:
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          ## Habits:
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          
          ## Calender:
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          ## Programming languages:
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage
          
          ## People:
          plugin_notable: yes
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          
          ## Projects:
          plugin_projects: no
          plugin_projects_limit: 4
          plugin_support: no

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Nothing yet

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo Test, and deploy your project.
